baseURL = 'https://blanclemjk.github.io/manifesto/'
languageCode = 'en-us'
title = 'M&W Manifesto'
theme = 'amethyst'

[module]
  [module.hugoVersion]
    extended = true
    min = "0.93.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1

[params]
  # Amethyst Theme Configuration
  name = "M&W Manifesto"
  enableLinkPreview = true
  enableLatex = true
  enableCodeBlockTitle = true
  enableCodeBlockCopy = true
  enableCallouts = true
  enableFooter = true
  enableContextualBacklinks = true
  enableMermaid = true
  
  # Navigation
  BookSection = "/" # Render all sections to menu
  BookToC = true

  # Overrides for Amethyst theme defaults
  links = []
  GitHubLink = "https://github.com/blanclemjk/manifesto"

[menu]
  [[menu.after]]
    name = "Github"
    url = "https://github.com/blanclemjk/manifesto"
    weight = 10
